version: '3'

services:
  mongodb-primary:
    image: mongo:4.0-rc
    command:
      - --replSet
      - mongoreplset
      - --smallfiles
      - --auth
      - --keyFile
      - /etc/mongodb-keyfile
      - --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=admin
      - TZ=Asia/Tokyo
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./primary/data/db:/data/db
      - ./key/mongodb-keyfile:/etc/mongodb-keyfile:ro
    expose:
      - 27017
    ports:
      - 27020:27017
    restart: always
  mongodb-secondary-1:
    image: mongo:4.0-rc
    command:
      - --replSet
      - mongoreplset
      - --smallfiles
      - --auth
      - --keyFile
      - /etc/mongodb-keyfile
      - --bind_ip_all
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./secondary-1/data/db:/data/db
      - ./key/mongodb-keyfile:/etc/mongodb-keyfile:ro
    expose:
      - 27017
    ports:
      - 27021:27017
    restart: always
  mongodb-secondary-2:
    image: mongo:4.0-rc
    command:
      - --replSet
      - mongoreplset
      - --smallfiles
      - --auth
      - --keyFile
      - /etc/mongodb-keyfile
      - --bind_ip_all
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./secondary-2/data/db:/data/db
      - ./key/mongodb-keyfile:/etc/mongodb-keyfile:ro
    expose:
      - 27017
    ports:
      - 27022:27017
    restart: always
  # mongodb-arbiter:
  #   image: mongo:4.0-rc
  #   command:
  #     - --replSet
  #     - mongoreplset
  #     - --smallfiles
  #     - --auth
  #     - --keyFile
  #     - /etc/mongodb-keyfile
  #     - --bind_ip_all
  #   environment:
  #     - TZ=Asia/Tokyo
  #   volumes:
  #     - ./key/mongodb-keyfile:/etc/mongodb-keyfile:ro
  #   expose:
  #     - 27017
  #   ports:
  #     - 27023:27017
  #   restart: always
